tap "anomalyco/tap"

# Herramientas del entorno.
brew "bat"
brew "carapace"
brew "cmatrix"
brew "diffnav"
brew "direnv"
brew "eza"
brew "fd"
brew "ffuf"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "herdr"
brew "lazygit"
brew "neovim"
brew "nushell"
brew "anomalyco/tap/opencode"
brew "ripgrep"
brew "starship"
brew "tree"
brew "xh"
brew "zoxide"
brew "zsh-autosuggestions"

cask "ghostty"
cask "font-jetbrains-mono-nerd-font"
cask "obsidian"
